language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: TOOLSET=g++-4.9
    
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: TOOLSET=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: TOOLSET=g++-6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: TOOLSET=g++-7
 
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env: TOOLSET=g++-8   

    - os: linux
      dist: trusty 
      compiler: clang 
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env: TOOLSET=clang-4.0
    
    - os: linux
      dist: trusty 
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-5.0']
          packages: ['clang-5.0']
      env: TOOLSET=clang-5.0

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-xenial']
          packages: ['clang-6.0']
      env: TOOLSET=clang-6.0

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-xenial-7']
          packages: ['clang-7']
      env: TOOLSET=clang-7

    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-xenial-8']
          packages: ['clang-8']
      env: TOOLSET=clang-8

install:
  - cd ../

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --no-check-certificate https://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar -xzf cmake-3.3.1-Linux-x86_64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CMAKE=$TRAVIS_BUILD_DIR/../cmake-3.3.1-Linux-x86_64/bin/cmake; fi

  - export CXX=$TOOLSET
  - $CXX --version
  - $CMAKE --version

  - cd warning_guards

script:
  - mkdir build/ && cd build/
  - $CMAKE -DCMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Werror" ../
  - $CMAKE --build .
